{{- if and .Values.terraria.password.enabled (not .Values.terraria.password.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraria-server.passwordSecretName" . }}
  labels:
    {{- include "terraria-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ include "terraria-server.password" . | quote }}
{{- end }}
