apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraria-server.fullname" . }}
  labels:
    {{- include "terraria-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: terraria
  selector:
    {{- include "terraria-server.selectorLabels" . | nindent 4 }}